// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase app
// ...
await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_RJgDhP75CXWaJTp9phoLBSb38vaLOk',
    appId: '1:74653326179:web:3aea1bec8528082ed39156',
    messagingSenderId: '74653326179',
    projectId: 'studentscanner-5ebb6',
    authDomain: 'studentscanner-5ebb6.firebaseapp.com',
    storageBucket: 'studentscanner-5ebb6.appspot.com',
    measurementId: 'G-ZYVHJPELXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBz-yPR_OQzFQy3jJ4rLKiwAIqX48lSXI',
    appId: '1:74653326179:android:6363416883957ed0d39156',
    messagingSenderId: '74653326179',
    projectId: 'studentscanner-5ebb6',
    storageBucket: 'studentscanner-5ebb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpG_7-nA1cEt1ZHiVeBeN8OnzOtBv7xc',
    appId: '1:74653326179:ios:ea10be71d4279d22d39156',
    messagingSenderId: '74653326179',
    projectId: 'studentscanner-5ebb6',
    storageBucket: 'studentscanner-5ebb6.appspot.com',
    iosBundleId: 'com.example.studentScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpG_7-nA1cEt1ZHiVeBeN8OnzOtBv7xc',
    appId: '1:74653326179:ios:ea10be71d4279d22d39156',
    messagingSenderId: '74653326179',
    projectId: 'studentscanner-5ebb6',
    storageBucket: 'studentscanner-5ebb6.appspot.com',
    iosBundleId: 'com.example.studentScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn_RJgDhP75CXWaJTp9phoLBSb38vaLOk',
    appId: '1:74653326179:web:d7d4774a6f1fcdedd39156',
    messagingSenderId: '74653326179',
    projectId: 'studentscanner-5ebb6',
    authDomain: 'studentscanner-5ebb6.firebaseapp.com',
    storageBucket: 'studentscanner-5ebb6.appspot.com',
    measurementId: 'G-D3E46DCELQ',
  );
}
